n1 = float(input("Insira a primeira nota: "))
n2 = float(input("Insira a segunda nota: "))
n3 = float(input("Insira a terceira nota: "))
n4 = float(input("Insira a qaurta nota: "))
print(f"A média das notas é: {(n1+n2+n3+n4)/4}")