print("=-="*20)
print("Este programa faz operações com 2 números inteiros e 1 real.")
print("=-="*20)
n1 = int(input("Digite o primeiro inteiro: "))
n2 = int(input("Digite o segundo inteiro: "))
n3 = float(input("Digite o número real: "))
print(f"O produto do dobro do primeiro com a metade do segundo é {2*n1*n2/2}")
print(f"A soma do triplo do primeiro com o terceiro é {3*n1+n3}")
print(f"O terceiro elevado ao cubo é {n3**3:.3f}")
